name: Deploy Next.js to AWS EB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 — Install Node.js 20
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3 — Confirm Node version
      - name: Check Node version
        run: node -v

      # Step 4 — Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5 — Build Next.js
      - name: Build project
        run: npm run build

      # Step 6 — Package deployment
      - name: Zip project
        run: zip -r deploy.zip . -x "*.git*"

      # Step 7 — Deploy to AWS EB
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "cloudaws"
          environment_name: "cloudenv"
          version_label: ${{ github.run_id }}
          region: "us-east-1"
          deployment_package: "deploy.zip"
